version: '3.7'

services:
    app:
        container_name: app
        build:
            dockerfile: Dockerfile
            context: .
        env_file: .env.docker
        ports:
            - 8080:8080
        volumes:
            - .:/home/app:cached
            - ./package.json:/home/app/package.json:cached
        depends_on:
          db:
            condition: service_healthy
        networks:
            - default_services_network

    db:
      image: postgres:14.4-alpine
      container_name: database
      # restart: always
      environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DATABASE: ${DB_NAME}
      volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      ports:
        - 5433:5432
      networks:
        - default_services_network
      healthcheck:
        test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
        interval: 5s
        timeout: 5s
        retries: 5


networks:
    default_services_network:
        name: crawler-services
