apiVersion: v1
kind: ConfigMap
metadata:
  name: desafio-npl-envs
  namespace: desafio-npl
data:
  PORT: '8081'
  NODE_ENV: 'production'
  DB_HOST: 'desafio-npl-db-svc'
  DB_PORT: '5432'
  DB_USER: 'postgres'
  DB_PASSWORD: 'docker'
  DB_NAME: 'crawler-db'
