apiVersion: v1
kind: Service
metadata:
  name: desafio-npl-svc
  namespace: desafio-npl
spec:
  selector:
    app: desafio-npl
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer
